spring.application.name=Trabindividual
#Porta do servidor
server.port=8080

#Conexao com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/TrabalhoIndividual
spring.datasource.username=postgres
spring.datasource.password=1234

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect